# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SchwarzMx
tagline:          'Where I blog...'
description:      'Musings about code and other things.<br>Follow me on <a href="https://twitter.com/schwarzmx" target="_blank">@schwarzmx</a>.'
url:              http://hyde.getpoole.com

author:
  name:           'Fernando Hernandez'
  url:            https://twitter.com/schwarzmx

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/schwarzmx/schwarzmx.github.com
